### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by SonZ3000** [Tfarcenim/Mob-Catcher#13]
when i try to catch a slime from better slimes it crashes
Mod: https://www.curseforge.com/minecraft/mc-mods/more-slimes

Error: Description: Exception in server tick loopDescription

java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.Entity.getPersistentData()" because the return value of "java.util.Optional.orElse(Object)" is null
	at net.mcreator.betterslimes.procedures.SynceatentagsProcedure.executeProcedure(SynceatentagsProcedure.java:55) ~[better_slimes:?] {re:classloading}
	at net.mcreator.betterslimes.procedures.SlimeinventoryIsOpenedProcedure$2.run(SlimeinventoryIsOpenedProcedure.java:86) ~[better_slimes:?] {re:classloading,pl:eventbus:A}
	at net.mcreator.betterslimes.procedures.SlimeinventoryIsOpenedProcedure$2.tick(SlimeinventoryIsOpenedProcedure.java:74) ~[better_slimes:?] {re:classloading,pl:eventbus:A}
	at net.minecraftforge.eventbus.ASMEventHandler_660__tick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:132) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1054) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}
stransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}
] {}

**Comment by Tfarcenim** [comment]
This is an issue with better slimes using mcreator, not my mod.
